// Code generated by MockGen. DO NOT EDIT.
// Source: ttanalytic/internal/service (interfaces: UpdaterRepository,TikTokProvider,Logger,Transactor)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	models "ttanalytic/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockUpdaterRepository is a mock of UpdaterRepository interface.
type MockUpdaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUpdaterRepositoryMockRecorder
}

// MockUpdaterRepositoryMockRecorder is the mock recorder for MockUpdaterRepository.
type MockUpdaterRepositoryMockRecorder struct {
	mock *MockUpdaterRepository
}

// NewMockUpdaterRepository creates a new mock instance.
func NewMockUpdaterRepository(ctrl *gomock.Controller) *MockUpdaterRepository {
	mock := &MockUpdaterRepository{ctrl: ctrl}
	mock.recorder = &MockUpdaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdaterRepository) EXPECT() *MockUpdaterRepositoryMockRecorder {
	return m.recorder
}

// AppendVideoStats mocks base method.
func (m *MockUpdaterRepository) AppendVideoStats(arg0 context.Context, arg1 models.CreateVideoStatsInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendVideoStats", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendVideoStats indicates an expected call of AppendVideoStats.
func (mr *MockUpdaterRepositoryMockRecorder) AppendVideoStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendVideoStats", reflect.TypeOf((*MockUpdaterRepository)(nil).AppendVideoStats), arg0, arg1)
}

// ListVideosForUpdate mocks base method.
func (m *MockUpdaterRepository) ListVideosForUpdate(arg0 context.Context, arg1 time.Duration, arg2 int) ([]models.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideosForUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideosForUpdate indicates an expected call of ListVideosForUpdate.
func (mr *MockUpdaterRepositoryMockRecorder) ListVideosForUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideosForUpdate", reflect.TypeOf((*MockUpdaterRepository)(nil).ListVideosForUpdate), arg0, arg1, arg2)
}

// SetVideoErrorStatus mocks base method.
func (m *MockUpdaterRepository) SetVideoErrorStatus(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoErrorStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVideoErrorStatus indicates an expected call of SetVideoErrorStatus.
func (mr *MockUpdaterRepositoryMockRecorder) SetVideoErrorStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoErrorStatus", reflect.TypeOf((*MockUpdaterRepository)(nil).SetVideoErrorStatus), arg0, arg1, arg2)
}

// UpdateVideoAggregates mocks base method.
func (m *MockUpdaterRepository) UpdateVideoAggregates(arg0 context.Context, arg1 models.UpdateVideoAggregatesInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoAggregates", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoAggregates indicates an expected call of UpdateVideoAggregates.
func (mr *MockUpdaterRepositoryMockRecorder) UpdateVideoAggregates(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoAggregates", reflect.TypeOf((*MockUpdaterRepository)(nil).UpdateVideoAggregates), arg0, arg1)
}

// MockTikTokProvider is a mock of TikTokProvider interface.
type MockTikTokProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTikTokProviderMockRecorder
}

// MockTikTokProviderMockRecorder is the mock recorder for MockTikTokProvider.
type MockTikTokProviderMockRecorder struct {
	mock *MockTikTokProvider
}

// NewMockTikTokProvider creates a new mock instance.
func NewMockTikTokProvider(ctrl *gomock.Controller) *MockTikTokProvider {
	mock := &MockTikTokProvider{ctrl: ctrl}
	mock.recorder = &MockTikTokProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTikTokProvider) EXPECT() *MockTikTokProviderMockRecorder {
	return m.recorder
}

// GetVideoStats mocks base method.
func (m *MockTikTokProvider) GetVideoStats(arg0 context.Context, arg1 string) (*models.VideoStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoStats", arg0, arg1)
	ret0, _ := ret[0].(*models.VideoStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoStats indicates an expected call of GetVideoStats.
func (mr *MockTikTokProviderMockRecorder) GetVideoStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoStats", reflect.TypeOf((*MockTikTokProvider)(nil).GetVideoStats), arg0, arg1)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), arg0...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactor) WithinTransaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactorMockRecorder) WithinTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactor)(nil).WithinTransaction), arg0, arg1)
}
